name: "Lint PR"

on:
  pull_request:

jobs:
  conventional-commits-check:
    name: Check conventional commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: "3.10"
      - name: Install commitizen
        run: pip install commitizen
      - name: commitizen check
        run: cz check --rev-range ${{ github.event.pull_request.base.sha }}..HEAD
